[project]
name = "ar-table-backend-service"
version = "0.1.0"

dependencies = [
    "numpy<2",
    "opencv-python==4.11.0.86",
    "websockets",
]

[tool.setuptools]
packages = ["service"]

[tool.setuptools.package-dir]
"" = "."
